services:
  app-dev:
    build:
      dockerfile: Dockerfile
      context: .
      # Only will build development stage from our dockerfile
      target: development
    volumes:
      - .:/home/go/sourcecode
      - ~/.ssh:/home/go/.ssh:ro
    depends_on:
      - mysql-dev
    networks:
      - backend
    ports:
      - 6464:6464
      - 6565:6565
      - 6767:6767
    command: godoc -http=:6464
  app-prod:
    build:
      dockerfile: Dockerfile
      context: .
      # Only will build production stage from our dockerfile
      target: production
    networks:
      - backend
    ports:
      - 6000:6000
  mysql-dev:
    image: mysql:5.7
    container_name: mysql-dev
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbdev
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    networks:
      - backend
networks:
  backend:
    driver: bridge
