services:
  app-dev:
    build:
      dockerfile: Dockerfile
      context: .
      # Only will build development stage from our dockerfile
      target: development
    volumes:
      - .:/home/go/sourcecode
    depends_on:
      - mysql-dev
    networks:
      - backend
    ports:
      - 6060:6060 # godoc
    command: godoc -http=:6060
  app-prod:
    build:
      dockerfile: Dockerfile
      context: .
      # Only will build production stage from our dockerfile
      target: production
    volumes:
      - .:/home/go/sourcecode
    networks:
      - backend
  mysql-dev:
    image: mysql:5.7
    container_name: mysql-dev
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbdev
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    networks:
      - backend
networks:
  backend:
    driver: bridge
